version: '3.3'

services:
  database:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "daizu"
      POSTGRES_PASSWORD: "soybeanslab"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  api:
    build: ./daizu-online-judge-backend
    ports:
      - 5042:5042
    restart: always
    command: python /daizu-online-judge-backend/src/app.py
    depends_on:
      - database
